[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "FAIR"
authors = [{name = "El Templato", email = "el@templato"}]
dynamic = ["version", "description"]
